### ISSUE TITLE
Link/Save/Import not available when running app locally?

### ISSUE THREAD

**Issue by dandavison** [joemccann/dillinger#297] opened 2015-02-19 23:09 UTC
I am running the dillinger node app locally (commit 9acc834ac4e7eff4f57086992f7aea1186b70272). None of the following page elements respond to a click. There are no javascript errors in the console.

- Services
- Export As
- Save To
- Import From

I was hoping to experiment with linking to google docs and/or github from a locally running dillinger instance. Should it just work or is there some configuration I need to do?

Incidentally I had to edit package.json so that angular-bootstrap 0.12.0 was installed instead of `^0.11.0`, see #296. Is the angular version the cause of the UI behavior reported here?

This may be similar to issues #207 #289.

Thanks, dillinger looks great!

**Comment by JuanCaicedo** [comment] 2015-02-21 19:22
I know that updating to angular-bootstrap 0.12.0 has broken some things for people in the past, like drop down menus. I think that's it's worth updating though, so I'll look into this as well.

**Comment by misterbisson** [comment] 2015-04-05 19:29
I'm seeing the same problem. I'd thought this was caused by the workaround I was using (suggested in https://github.com/joemccann/dillinger/issues/309#issuecomment-81779702) to build it, but I'm still seeing the problem after the fixes for that have been merged.

Screenshots, for clarity:

![screen shot 2015-04-05 at 12 24 55 pm](https://cloud.githubusercontent.com/assets/1709697/6998267/51de9908-db8f-11e4-862b-74e857b26d4c.png)

![screen shot 2015-04-05 at 12 25 46 pm](https://cloud.githubusercontent.com/assets/1709697/6998268/55f48a5c-db8f-11e4-8358-b952b18bacf1.png)

**Comment by misterbisson** [comment] 2015-05-25 19:13
It looks like @steinwaywhw has [tracked down](https://github.com/joemccann/dillinger/pull/321#issuecomment-100315452) the root cause of this issue: https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#breaking-changes

**Comment by joemccann** [comment] 2015-05-25 22:59
I merged this and now all dropdowns are broken on dillinger.io

**Comment by joemccann** [comment] 2015-05-25 23:15
I rolled back to the point of just the Dockerfile updates.

Also, dillinger.io is running on node 0.10.36 so if this is an 0.12 issue then we'll need to sort it there first.

**Comment by benjamin-albert** [comment] 2016-05-09 06:34
Link, Save and Import  features will only show up if they are configured (which they aren't when you clone the repo).

I also noticed that we are using angular-bootstrap 0.12.2 and all dropdowns work fine (when there services are configured).

This issue has been inactive quite a while so I'm closing it.

**Closed by benjamin-albert** 2016-05-09 06:34 UTC
