### ISSUE TITLE
Exporting documents with escaped characters in the name result in 404 or 400 for the exported document.

### ISSUE THREAD

**Issue by Raane** [joemccann/dillinger#502] opened 2016-02-11 09:51 UTC
If a document has a name containing escaped special characters the export fails. The application behave as if all is fine, but no file is actually downloaded because the request return a 404 or 400 error code.

A document named untitled\\_document.md will return a 404 when attempted exported.

A document named untitled\%document.md will return a 400 when attempted exported.

**Comment by joemccann** [comment] 2016-02-11 17:21
I'm unable to reproduce the 404 but I *am* able to reproduce the 400.  This
is a bug.

**Comment by Raane** [comment] 2016-02-15 14:54
Sorry. I forgot that the issue tracker on Github uses markdown as well. My "\\_" in the issue became a "_" in the view on GitHub.

The bug is present occur with escaped underscores. The issue has been updated.

**Comment by benjamin-albert** [comment] 2016-05-04 13:32
Looks like #502 and #511 fix this issue.  I'm closing this now.

**Closed by benjamin-albert** 2016-05-04 13:32 UTC
