### ISSUE TITLE
doesn't show all the repos from github

### ISSUE THREAD

**Issue by mseshachalam** [joemccann/dillinger#412] opened 2015-10-23 16:27 UTC

**Comment by tlongren** [comment] 2015-11-07 21:06
Likely a duplicate of #284, which was closed by #416. Will be closing this soon unless @mseshachalam has more to add.

**Comment by tlongren** [comment] 2015-11-08 08:33
Going to close this issue as it's very likely that @mseshachalam is referring to problems described in issue #415, which was recently closed by pull request #416.

If you were experiencing something different, @mseshachalam, just comment and let me know. Thanks!

**Closed by tlongren** 2015-11-08 08:33 UTC
