### ISSUE TITLE
Locally hosted installs serving ads

### ISSUE THREAD

**Issue by thelamer** [joemccann/dillinger#746] opened 2020-01-12 00:11 UTC
LinuxServer.io team here. https://github.com/linuxserver/docker-dillinger 
We had a report that a users local install is serving ads , I have not been able to replicate it locally but it does look like the sponsored plugin in in the codebase we ingest. 
While I am 100% on board with projects that a group of developers pour their hearts into turning revenue to support the project, we would like to have default installs have this functionality off maybe replaced by a donation link if possible.

Essentially just looking for a quick guide for turning this on/off so we can automate it via an ENV var if users choose to turn it on.

**Comment by joemccann** [comment] 2020-01-12 00:15
Not sure how this is possible unless I mistakenly hardcoded the API key for
the ads!?

It reads from a config file.

A fresh install for me doesn't serve ads?

**Comment by thelamer** [comment] 2020-01-12 00:17
As I said I cannot replicate it. Let me close this and keep following up with the user.

**Comment by AlexKalopsia** [comment] 2020-01-12 11:21
I am the user having the issue. Writing here because it's easier to keep track of things. 

I can confirm I am not being redirected to dillinger.io. I am on `192.16.1.200:8180`

I have tested on Firefox and Edge, I can confirm I am still getting ads on the top navbar

It is my first install.

this is my log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
 
 
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
 
User uid:    1027
User gid:    100
-------------------------------------
 
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Dropbox config not found at /app/dillinger/configs/dropbox/dropbox-config.json. Plugin disabled.
Bitbucket config not found at /app/dillinger/configs/bitbucket/bitbucket-config.json. Plugin disabled.
Github config not found at /app/dillinger/configs/github/github-config.json. Plugin disabled.
Medium config not found at /app/dillinger/configs/medium/medium-config.json. Plugin disabled.
Google Drive config not found at /app/dillinger/configs/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /app/dillinger/configs/onedrive/onedrive-config.json. Plugin disabled.
GoogleAnalytics config not found at /app/dillinger/configs/googleanalytics/googleanalytics-config.json. Plugin disabled.
Sponsored config not found at /app/dillinger/configs/sponsored/sponsored-config.json. Plugin disabled.
Express server listening on port 8080
 
http://localhost:8080
 
::ffff:172.17.0.1 - GET / HTTP/1.1 200 - - 476.348 ms
::ffff:172.17.0.1 - GET /assets/app-34f98342c2410debfb8d88b906d178e0.css HTTP/1.1 200 73012 - 3.356 ms
::ffff:172.17.0.1 - GET /img/icons/file.svg HTTP/1.1 200 - - 11.888 ms
::ffff:172.17.0.1 - GET /js/main.bundle.js HTTP/1.1 200 - - 6.638 ms
::ffff:172.17.0.1 - GET /apple-touch-icon.png HTTP/1.1 200 5779 - 22.511 ms
::ffff:172.17.0.1 - GET /img/icons/enter-zen.svg HTTP/1.1 200 - - 8.663 ms
::ffff:172.17.0.1 - GET /img/icons/code.svg HTTP/1.1 200 902 - 19.595 ms
::ffff:172.17.0.1 - GET / HTTP/1.1 304 - - 123.372 ms
::ffff:172.17.0.1 - GET /assets/app-34f98342c2410debfb8d88b906d178e0.css HTTP/1.1 200 73012 - 2.929 ms
::ffff:172.17.0.1 - GET /js/main.bundle.js HTTP/1.1 304 - - 3.590 ms
::ffff:172.17.0.1 - GET /img/icons/file.svg HTTP/1.1 200 - - 16.983 ms
::ffff:172.17.0.1 - GET /apple-touch-icon.png HTTP/1.1 - - - - ms
::ffff:172.17.0.1 - GET /img/icons/enter-zen.svg HTTP/1.1 304 - - 2.771 ms
::ffff:172.17.0.1 - GET /img/icons/code.svg HTTP/1.1 304 - - 1.439 ms
```

**Comment by joemccann** [comment] 2020-01-12 15:03
Without a screencapture video I don't know what to say!  It's a simple conditional check in the source code to see if the config exists, then include the markup for ads, otherwise, the code isn't even in the markup.  It's been like this for years.

Please provide a screencap video, screenshots of the markup, screenshots of a web inspector view, etc.

Thanks!

**Comment by AlexKalopsia** [comment] 2020-01-12 15:53
Here a video. Not sure if this contains the info you were looking for

https://www.youtube.com/watch?v=_mv_BEWjcUY

**Comment by joemccann** [comment] 2020-01-12 16:04
I think I know what the issue is but it seems super odd -- maybe at some point when I pushed the docker image to docker hub I included the ad code?  When I run this locally just using node this doesn't happen.  Yet you are running this with docker.  Can you run it locally with just node, build the file locally and run with docker to see if the issue persists?

**Comment by joemccann** [comment] 2020-01-12 16:11
Actually, I take that back!  Brave was blocking the ad locally.  When I opened localhost in Chrome the ad is there.  Ok, let me take a look at this.  I must have committed by accident somehow.

**Comment by joemccann** [comment] 2020-01-12 17:43
Ok @AlexKalopsia I found the issue.  Way back in March of 2017 I had to refactor the sponsored plugin code and it turned out...it had a bug...which was including the account ID in the code itself.

Nonetheless, have a look a v3.37.0.  LMK if it fixes your issue and we can close this issue.

**Comment by AlexKalopsia** [comment] 2020-01-12 17:45
Good, cause I would have no idea how to run this other than Docker XD

**Comment by joemccann** [comment] 2020-01-12 17:45
doing some merging...one sec

**Comment by joemccann** [comment] 2020-01-12 17:51
Ok ready to go

**Comment by AlexKalopsia** [comment] 2020-01-12 21:05
Can confirm the latest fixed the issue, thank you!

**Comment by joemccann** [comment] 2020-01-13 02:16
💯💯💯

**Closed** 2020-01-14 18:04 UTC
